env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "V9jC7zKYRc-QTXf5OkldrQ"
language: cpp

install:
  - sudo apt-get update
  - sudo apt-get install g++ libtool autoconf automake libmysqlclient-dev exuberant-ctags libxml2-dev pkg-config make
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
compiler: gcc
os: linux
sudo: required

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.8
        - g++-4.8
  coverity_scan:
    project:
        name: "rajesh6115/myesme"
        description: "Build submitted via Travis CI"
    notification_email: sahoorajesh.d@gmail.com
    build_command_prepend: "autoreconf -i && ./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
    
before_script:
  - autoreconf -iv
  
script: autoreconf -i && ./configure && make 

branches:
  only:
    - master
    - coverity_scan
