#ifndef _DEFINES_HPP_
#define _DEFINES_HPP_
#define MAX_SMS_CAMPAIGN 5
#define MAX_CAMPAIN_ERROR 3
#define SMS_CAMPAIGN_WINDOW_SIZE 500
#define SMS_CAMPAIGN_QUEUE_SIZE 3000
#define SMS_CAMPAIGN_ENQUEUE_SLEEP 1
#define SMS_CAMPAIGN_ENQUEUE_USLEEP 200000
// For Picking Same Campaign Again
#define SMS_CAMPAIGN_PICK_SLEEP 60

#define CAMPAIGN_WINDOW_SLEEP 1
#define CAMPAIGN_WINDOW_USLEEP 500000
#define DFL_USLEEP_VALUE 500000
#define DFL_SLEEP_VALUE 3
#define DFL_LIVE_SLEEP_VALUE 30
#define DFL_SMPP_URL "127.0.0.1"
#define DFL_SMPP_PORT 2775
#define MAX_READ_BUFFER_LENGTH 1024
#define MAX_PDU_PRACTICAL_LENGTH 5000
#define MIN_PDU_LENGTH 16

#define ESME_MAX_NO_OF_INSTANCE 10
#define NO_ESME_INSTANCE_SLEEP 10
#define MULTI_READ_TIME_OUT_SEC 3
#define NO_SMS_QUEUE_USLEEP 700000
#define SEND_PAUSE_USLEEP 100000
#define RESEND_USLEEP 20000
#define PDU_PROCESS_USLEEP 10000
#define ESME_DFL_TPS 1000

#endif
