#ifndef _DEFINES_HPP_
#define _DEFINES_HPP_
#define CAMPAIGN_ST_SCHEDULED 1
#define CAMPAIGN_ST_PICKED 2
#define CAMPAIGN_ST_COMPLETED 10
#define MAX_CAMPAIN_ERROR 3
#define SMS_CAMPAIGN_WINDOW_SIZE 100
#define DFL_USLEEP_VALUE 500000
#define DFL_SLEEP_VALUE 3
#define DFL_LIVE_SLEEP_VALUE 30
#define DFL_SMPP_URL "127.0.0.1"
#define DFL_SMPP_PORT 2775
#define DFL_MSGID_QUE_NAME "/msgidqueue"
#define DFL_MSGID_QUE_MSG_SIZE 256
#define DFL_MSGID_QUE_NO_OF_MSG 1000
/*
#define BIND_RDONLY 1
#define BIND_WRONLY 2
#define BIND_RDWR 3
*/
#define MAX_READ_BUFFER_LENGTH 256
#define MAX_PDU_PRACTICAL_LENGTH 5000
#define MIN_PDU_LENGTH 16
#endif
